version: '3.8'

name: neuromesh

services:

  tgbot-service:
    container_name: tgbot-service
    hostname: tgbot
    depends_on:
      rabbitmq:
        condition: service_healthy
    build: 
      context: ./tgbot/
      dockerfile: ./Dockerfile
    env_file:
      - ./tgbot/.env
    networks:
      - internal
      - default

  api-service:
    &api-service
    container_name: api-service
    hostname: api
    depends_on:
      rabbitmq:
        condition: service_healthy
      postgres: 
        condition: service_healthy
    build: 
      context: ./api/
      dockerfile: ./Dockerfile
    env_file:
      - ./api/.env.production
    networks:
      - internal
      - default
    command: sh -c "alembic upgrade head && uvicorn --factory presentation.main:create_app --host 0.0.0.0 --port 8080"

  rabbitmq:
    container_name: rabbitmq-service
    image: rabbitmq:3.8.27-management-alpine
    hostname: rabbitmq
    env_file:
      - .env
    networks:
      - internal
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_USER:-admin}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASSWORD:-admin}
    # volumes:
    #   - rabbitmq.data:/var/lib/rabbitmq/:rw
    healthcheck:
      test: ["CMD-SHELL", "rabbitmq-diagnostics check_running -q"]
      interval: 10s
      timeout: 60s
      retries: 5
      start_period: 10s
  
  postgres:
    container_name: postgres
    build: ./postgresql/
    hostname: postgres
    env_file:
      - ./api/.env.production
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    networks:
      - internal
    command: postgres -c 'config_file=/etc/postgresql/postgresql.conf'
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      interval: 10s
      timeout: 60s
      retries: 5
      start_period: 10s

  text2image-worker:
    <<: *api-service
    ports: []
    container_name: text2image-worker
    command: taskiq worker infrastructure.tasks.main:broker infrastructure.tasks.tasks
    depends_on:
      rabbitmq:
        condition: service_healthy
    
volumes:
  rabbitmq.data: {}
  postgres_data:

networks:
  internal:
    driver: bridge
    internal: true
  default:
    driver: bridge
