version: '3.8'

name: neuromesh

services:

  bot:
    depends_on:
      rabbitmq:
        condition: service_healthy
    build: 
      context: ./tgbot
      dockerfile: ./.ci/Dockerfile
    volumes:
      - ./tgbot/src:/app
    env_file:
      - .env
    networks:
      - internal

  api:
    &api
    depends_on:
      rabbitmq:
        condition: service_healthy
    build: 
      context: ./api
      dockerfile: ./.ci/Dockerfile
    env_file:
      - .env
    networks:
      - internal
    ports:
      - 8000:8000
    volumes:
      - ./api/src:/app

  postgres:
    image: postgres:16-bookworm
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    networks:
      - internal
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      interval: 10s
      timeout: 60s
      retries: 5
      start_period: 10s

  rabbitmq:
    image: rabbitmq:3.8.27-management-alpine
    networks:
      - internal
    env_file:
      - .env
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_USER:-admin}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASSWORD:-admin}
    healthcheck:
      test: ["CMD-SHELL", "rabbitmq-diagnostics check_running -q"]
      interval: 10s
      timeout: 60s
      retries: 5
      start_period: 10s

  taskiq-worker:
    <<: *api
    ports: []
    command: taskiq worker infrastructure.tasks.main:broker infrastructure.tasks.tasks
    depends_on:
      rabbitmq:
        condition: service_healthy

  grafana:
    image: grafana/grafana:9.5.2
    ports:
      - 3000:3000
    networks:
      - internal
    volumes:
      - neuromesh.grafana.data:/var/lib/grafana:rw
      - ./config/grafana/provisioning:/etc/grafana/provisioning:rw
    environment:
      - GF_USERS_ALLOW_SIGN_UP=false
      - VIRTUAL_HOST=neuromesh.grafana
      - NETWORK_ACCESS=internal
      - VIRTUAL_PORT=3000

  loki:
    image: grafana/loki:2.8.2
    volumes:
      - logs_data:/var/log
    networks:
      - internal
    
  # scheduler:
  #   container_name: scheduler
  #   build: ./scheduler
  #   hostname: scheduler
  #   networks:
  #     - internal
  #   depends_on:
  #     rabbitmq:
  #       condition: service_healthy
    
volumes:
  neuromesh.loki.data: {}
  neuromesh.grafana.data: {}
  rabbitmq.data: {}
  postgres_data:

networks:
  internal:
    driver: bridge
