"""empty message

Revision ID: 6d9472154a01
Revises: 
Create Date: 2024-07-19 02:01:39.103895

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6d9472154a01'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('neural_networks',
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('name')
    )
    op.create_index(op.f('ix_neural_networks_name'), 'neural_networks', ['name'], unique=False)
    op.create_table('subscriptions',
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('name')
    )
    op.create_index(op.f('ix_subscriptions_name'), 'subscriptions', ['name'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('telegram_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('current_subscription', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_telegram_id'), 'users', ['telegram_id'], unique=False)
    op.create_table('neural_networks_subscriptions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('neural_network_name', sa.String(), nullable=False),
    sa.Column('subscription_name', sa.String(), nullable=False),
    sa.Column('requests', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['neural_network_name'], ['neural_networks.name'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subscription_name'], ['subscriptions.name'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_neural_networks_subscriptions_id'), 'neural_networks_subscriptions', ['id'], unique=False)
    op.create_table('users_requests',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('neural_network_name', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['neural_network_name'], ['neural_networks.name'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_requests_id'), 'users_requests', ['id'], unique=False)
    op.create_table('users_subscriptions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('subscription_name', sa.String(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_in', sa.TIMESTAMP(), nullable=False),
    sa.Column('is_expired', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['subscription_name'], ['subscriptions.name'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_subscriptions_id'), 'users_subscriptions', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_subscriptions_id'), table_name='users_subscriptions')
    op.drop_table('users_subscriptions')
    op.drop_index(op.f('ix_users_requests_id'), table_name='users_requests')
    op.drop_table('users_requests')
    op.drop_index(op.f('ix_neural_networks_subscriptions_id'), table_name='neural_networks_subscriptions')
    op.drop_table('neural_networks_subscriptions')
    op.drop_index(op.f('ix_users_telegram_id'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_subscriptions_name'), table_name='subscriptions')
    op.drop_table('subscriptions')
    op.drop_index(op.f('ix_neural_networks_name'), table_name='neural_networks')
    op.drop_table('neural_networks')
    # ### end Alembic commands ###
